### ISSUE TITLE
DID Modal

### ISSUE THREAD

**Issue by thereisnogabe** [TBD54566975/ssi-admin-ui#10]
# Tasks
- [x] Move Create DID modal to component
- [x] Move Import DID modal to component
- [ ] Add error handling
- [ ] Add UI validation design elements
- [ ] Get UI feedback on design components
- [x] Add more mock data to test
- [ ] Add documentation
- [ ] Write unit tests for Create DID
- [ ] Write unit tests for Import DID
- [ ] Write E2E playwright test for Create DID 
- [ ] Write E2E playwright test for Import DID
