### ISSUE TITLE
Credential Issuance Modal

### ISSUE THREAD

**Issue by thereisnogabe** [TBD54566975/ssi-admin-ui#8]
# Tasks
- [x] Move Issue Credential to modal component
- [ ] Add error handling
- [ ] Add UI validation design elements
- [ ] Get UI feedback on design components
- [x] Add more mock data to test
- [ ] Add documentation
- [ ] Write unit tests for Issue Credential
- [ ] Write E2E playwright test for Issue Credential
