### ISSUE TITLE
Schema Modal

### ISSUE THREAD

**Issue by thereisnogabe** [TBD54566975/ssi-admin-ui#9]
# Tasks
- [x] Move Create Schema to modal component
- [ ] Add error handling
- [ ] Add UI validation design elements
- [ ] Get UI feedback on design components
- [ ] Add more mock data to test
- [ ] Add documentation
- [ ] Write unit tests for Create Schema
- [ ] Write E2E playwright test for Create Schema
